import streamlit as st
import torch
import numpy as np
import torch.nn.functional as F
from model import BreastCancerClassifier

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Breast Cancer Prediction",
    page_icon="🩺",
    layout="centered"
)

# ---------------- LOAD MODEL ----------------
@st.cache_resource
def load_model():
    model = BreastCancerClassifier(
        input_features=30,
        hidden_features=20,
        output_features=2
    )
    model.load_state_dict(
        torch.load("model.pth", map_location=torch.device("cpu"))
    )
    model.eval()
    return model

model = load_model()

# ---------------- UI ----------------
st.title("🩺 Breast Cancer Identification App")
st.write("Predict whether a tumor is **Benign or Malignant** using a PyTorch model.")

st.divider()

feature_names = [
    "Mean Radius", "Mean Texture", "Mean Perimeter", "Mean Area", "Mean Smoothness",
    "Mean Compactness", "Mean Concavity", "Mean Concave Points", "Mean Symmetry", "Mean Fractal Dimension",
    "Radius SE", "Texture SE", "Perimeter SE", "Area SE", "Smoothness SE",
    "Compactness SE", "Concavity SE", "Concave Points SE", "Symmetry SE", "Fractal Dimension SE",
    "Worst Radius", "Worst Texture", "Worst Perimeter", "Worst Area", "Worst Smoothness",
    "Worst Compactness", "Worst Concavity", "Worst Concave Points", "Worst Symmetry", "Worst Fractal Dimension"
]

features = []

st.subheader("🔢 Enter Medical Features")

for name in feature_names:
    value = st.number_input(name, min_value=0.0, format="%.4f")
    features.append(value)

st.divider()




# ---------------- PREDICTION ----------------
if st.button("🔍 Predict", use_container_width=True):
    input_data = np.array(features, dtype=np.float32).reshape(1, -1)
    input_tensor = torch.tensor(input_data)

    with torch.no_grad():
        outputs = model(input_tensor)
        probs = F.softmax(outputs, dim=1)
        pred = torch.argmax(probs, dim=1).item()

    st.subheader("🧾 Prediction Result")

    if pred == 0:
        # Malignant
        st.error("🚨 **CANCER DETECTED (Malignant Tumor)**")
        st.markdown(
            f"""
            **Confidence:** `{probs[0][0]*100:.2f}%`

            ⚠️ This result indicates a **high risk of breast cancer**.  
            Please consult a **qualified medical professional immediately**.
            """
        )
    else:
        # Benign
        st.success("✅ **NO CANCER DETECTED (Benign Tumor)**")
        st.markdown(
            f"""
            **Confidence:** `{probs[0][1]*100:.2f}%`

            ✔️ This result indicates **low risk of breast cancer**.  
            Regular check-ups are still recommended.
            """
        )

    st.info(
        "ℹ️ **Disclaimer:** This prediction is generated by a machine learning model "
        "and should NOT be considered a medical diagnosis."
    )
